version: "4.33.1"
services:
  nginx:
    container_name: nginx-desafio
    image: nginx:1.27.0
    volumes:
      - ./staticfiles:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  database:
    container_name: desafio
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=desafio
      - POSTGRES_USER=desafio
      - POSTGRES_DB=desafio
    ports:
      - 5432:5432