# Generated by Django 5.0.7 on 2024-07-27 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('banner', models.ImageField(upload_to='banners/')),
                ('regras_pontuacao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('pontuacao', models.IntegerField(default=0)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desafio')),
            ],
        ),
        migrations.AddField(
            model_name='corretor',
            name='desafios',
            field=models.ManyToManyField(through='core.ParticipacaoDesafio', to='core.desafio'),
        ),
    ]
